Replace KDE and Xorg with Sway and Wayland
* Removes SDDM
* Removes vagrant-guest configs since Sway needs to be run in QEMU
* Alacritty doesn't run in Wayland yet, so adds Termite as default
  terminal

TODOs:

* Brightness controls still need to be tested and maybe fixed:
    * Calise for ambient brightness adjustment
    * Illum for manual brightness adjustment
    * Redshift for time-of-day gamma adjustment
* Replace xdotool with ??? for libinput-gestures

diff --git a/files/wait-for-internet b/files/wait-for-internet
--- a/files/wait-for-internet
+++ b/files/wait-for-internet
@@ -12,9 +12,9 @@ done
 
 echo "All network interfaces up"
 
-until ping -c 1 google.com >/dev/null 2>/dev/null; do
-  >&2 echo "Ping google.com failed"
+until curl --silent --fail --max-time 1 https://www.google.com >/dev/null 2>/dev/null; do
+  >&2 echo "Curl https://www.google.com failed"
   sleep 1
 done
 
-echo "Successfully pinged google.com"
+echo "Successfully reached https://www.google.com"
